name = {
		"1"   : "Amulet Of Air",
		"2"   : "Amulet Of Fire",
		"3"   : "Amulet Of Earth",
		"4"   : "Amulet Of Water",
		"5"   : "Balance Of Ishtar",
		"6"   : "Staff Of Spring",
		"7"   : "Temporal Boots",
		"8"   : "Purse Of Io",
		"9"   : "Divine Chalice",
		"10"  : "Syllas the Faithful",
		"11"  : "Figrim The Avaricious",
		"12"  : "Naria The Prophetess",
		"13"  : "Wondrous Chest",
		"14"  : "Beggar’s Horn",
		"15"  : "Dice of Malice",
		"16"  : "Kairn the Destroyer",
		"17"  : "Amsug Longneck",
		"18"  : "Bespelled Grimoire",
		"19"  : "Ragfield’s Helm",
		"20"  : "Hand of Fortune",
		"21"  : "Lewis Grayface",
		"22"  : "Runic Cube Of Eolis",
		"23"  : "Potion of Power",
		"24"  : "Potion Of Dreams",
		"25"  : "Potion of Knowledge",
		"26"  : "Potion Of Life",
		"27"  : "Hourglass Of Time",
		"28"  : "Scepter Of Greatness",
		"29"  : "Olaf’s Blessed Statue",
		"30"  : "Yjang’s Forgotten Vase",
		"31"  : "Elemental Amulet",
		"32"  : "Tree of Light",
		"33"  : "Arcano Leech",
		"34"  : "Crystal Orb",
		"35"  : "Glutton Cauldron",
		"36"  : "Vampiric Crown",
		"37"  : "Dragon Skull",
		"38"  : "Demon Of Argos",
		"39"  : "Titus Deepgaze",
		"40"  : "Air Elemental",
		"41"  : "Thieving Fairies",
		"42"  : "Cursed Treatise of Arus",
		"43"  : "Idol Of The Familiar",
		"44"  : "Necrotic Kriss",
		"45"  : "Lantern Of Xidit",
		"46"  : "Sealed Chest Of Urm",
		"47"  : "Mirror Of The Seasons",
		"48"  : "Pendant Of Ragnor",
		"49"  : "Sid Nightshade",
		"50"  : "Damned Soul Of Onys",
		"101" : "Heart of Argos",
		"102" : "Horn of Plenty",
		"103" : "Fairy Monolith",
		"104" : "Selenia’s Codex",
		"105" : "Scroll of Ishtar",
		"106" : "Mesodae’s Lantern",
		"107" : "Statue of Eolis",
		"108" : "Familiar Catcher",
		"109" : "Io’s Transmuter",
		"110" : "Throne of Renewal",
		"111" : "Potion of Resurrection",
		"112" : "Jewel of the Ancients",
		"113" : "Shield of Zira",
		"114" : "Steadfast Die",
		"115" : "Amulet of Time",
		"116" : "Arcane Telescope",
		"117" : "Argos Hawk",
		"118" : "Raven the Usurper",
		"119" : "Warden of Argos",
		"120" : "Ratty Nightshade",
		"201" : "Dragonsoul",
		"202" : "Magma Core",
		"203" : "Twist of Fate",
		"204" : "Potion of the Ancients",
		"205" : "Ethiel’s Fountain",
		"206" : "Dial of Colof",
		"207" : "Chalice of Eternity",
		"208" : "Staff of Winter",
		"209" : "Sepulchral Amulet",
		"210" : "Eolis’s Replicator",
		"211" : "Estorian Harp",
		"212" : "Chrono-Ring",
		"213" : "Arus’s Mimicry",
		"214" : "Carnivora Strombosea",
		"215" : "Urmian Psychic Cage",
		"216" : "Servant of Ragfield",
		"217" : "Argosian Tangleweed",
		"218" : "Io’s Minion",
		"219" : "Otus the Oracle",
		"220" : "Malicious Nightshade",
		"221" : "Igramul the Banisher",
		"222" : "Replicator",
		"301" : "Speedwall the Escaped",
		"302" : "Orb of Ragfield",
		"303" : "Crystal Titan",
}
